### ISSUE TITLE
Running mytest.R Error in session_makeRequest(self, private, endpoint, data, params, headers) :    Unable to find input binding for element with id logInusername

### ISSUE THREAD

**Issue by avijandiran** [rstudio/shinytest#269]
Running mytest.R Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element with id logInusername

I have seen similar issues with this same error. But I have given Sys.sleep(), I have Id for the text input. But I still can't clear this issue. I am using in Rstudio server. 

**sample ui code:**

    fluidRow(column(width = 4, offset = 4,
                    textInput(inputId = "l**ogInusername**",
                              label = NULL,
                              placeholder = "Username",
                              width = "100%"))),
    fluidRow(column(width = 4, offset = 4,
                    passwordInput(inputId = "logInpassword",
                                  label = NULL,
                                  placeholder = "Password",
                                  width="100%"))),
    fluidRow(column(width = 4, offset = 4,
                    withBusyIndicatorUI(actionButton(inputId = "logInsignin",
                                                     label = "Sign in",
                                                     width = "100%")))),

**mytest.R:** 

```R
app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("mytest")

app$setInputs(`shinyjs-delay-7d6bf25dd352289f27fa1079d1776afb` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`shinyjs-delay-a9ab5cb4170bbf76f95465c5dcff2d42` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`shinyjs-delay-b0c6e461a5612af5742a18fbcb4204b5` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
Sys.sleep(2)
app$setInputs(logInusername = "admin",wait_=FALSE, values_=FALSE)
app$setInputs(logInpassword = "12345")
app$setInputs(logInsignin = "click")
app$setInputs(`shinyjs-logInsignin-307212834-input-click` = c(0, 0, 0, 484, 0, 484, 485, 484, 558, 0, 1, 0.625233043922833), allowInputNoBinding_ = TRUE)
app$setInputs(`shinyjs-delay-10f96c8e181d5908cae23ab9dbfc267a` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(analySide_btn_loadDCP = "click")
app$setInputs(analySide_dateRange_loadData = "2019-07-10")
app$setInputs(analySide_dateRange_loadData = character(0))
app$setInputs(analySide_dateRange_loadData = "2017-12-11")
app$setInputs(analySide_dateRange_loadData = c("2017-12-11", "2017-12-12"))
app$setInputs(`shinyjs-delay-162f5df5d52f29fde9eb0a564ea709e5` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(analySide_btn_loadData = "click")
app$setInputs(`shinyjs-delay-13459ba7e3e3812ef56527eaa206cd24` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$snapshot()
```

**Comment by wch** [comment]
It would help if you can provide a reproducible example -- that is, an entire working application. Please see: https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001

**Comment by avijandiran** [comment]
I can't post the entire application it's huge. What understand as of now is,

**allowInputNoBinding_ means:** 
When setting the value of an input, allow it to set the value of an input
even if that input does not have an input binding.

As per the Reference: [https://rstudio.github.io/shinytest/articles/in-depth.html]

 I changed all the app$setInputs to (allowInputNoBinding_ = TRUE) as shown here:
 just a simple login to rstudio server using the username and password.

Now i don't get any error ...But why i need to give (allowInputNoBinding_ = TRUE) to all my app$setInput ??? is my question . 

**mytest.R**

app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(`shinyjs-delay-b605f5e97118a4b130701885eb1be7f9` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`shinyjs-delay-47e3e2b13cf857d2500d2bad708296fa` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`shinyjs-delay-5d154375d374a1e78d88c9bfc3f383a1` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`shinyjs-delay-c1c33ebb91d153116a693b28e23b9d56` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)

app$setInputs(logInusername = "admin",wait_=FALSE, values_=FALSE,allowInputNoBinding_ = TRUE)
app$setInputs(logInpassword = "12345",wait_=FALSE, values_=FALSE,allowInputNoBinding_ = TRUE)
app$setInputs(logInsignin = "click",wait_=FALSE, values_=FALSE,allowInputNoBinding_ = TRUE)

app$setInputs(`shinyjs-logInsignin-411173489-input-click` = 0.691770015757014, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)

app$setInputs(`shinyjs-delay-4b6012011694a49d0d04de423dd941b6` = 2000, allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$snapshot()

**Comment by emanko** [comment]
I would be interested with follow-up regarding this issue as I am encountering similar problem with `session_makeRequest` since moving to 1.3.1 version. Tests for my app were implemented whilst working with 1.3.0.9002 version. 
I was able to prepare simple reproducible example with custom test written using `shinytest` and `testthat` packages.
Code fails at ```app$setInputs(`.clientValue-plotly_click-barplot` = click_event, allowInputNoBinding_ = TRUE)``` and I receive similar error for all the tests that use allowInputNoBinding_ which did not happen before. 

I would appreciate any suggestions!

**Error message:**
```r
test-app.R:22: error: Check if clicking on plotly filters data table
undefined is not a function (evaluating 'Shiny.setInputValue(item.name, item.value, priority)')
1: app$setInputs(`.clientValue-plotly_click-barplot` = click_event, allowInputNoBinding_ = TRUE) at tests/testthat/test-app.R:22
2: sd_setInputs(self, private, ..., wait_ = wait_, values_ = values_, timeout_ = timeout_, allowInputNoBinding_ = allowInputNoBinding_, priority_ = priority_)
3: private$flushInputs(wait_, timeout_)
4: sd_flushInputs(self, private, wait, timeout)
5: private$web$executeScriptAsync("var wait = arguments[0];\n    var timeout = arguments[1];\n    var callback = arguments[2];\n    shinytest.outputValuesWaiter.start(timeout);\n    shinytest.inputQueue.flush();\n    shinytest.outputValuesWaiter.finish(wait, callback);", 
       wait, timeout)
6: session_executeScriptAsync(self, private, script, ...)
7: private$makeRequest("EXECUTE ASYNC SCRIPT", list(script = script, args = args))
8: session_makeRequest(self, private, endpoint, data, params, headers)
9: report_error(response)
```

**app.R**
```r
library(DT)
library(plotly)
library(dplyr)

ui <- pageWithSidebar(
  headerPanel('Test'),
  sidebarPanel(
    selectInput('category', 'Category', names(iris)[which(names(iris) != 'Species')]),
    uiOutput("threshold")
  ),
  mainPanel(
    plotlyOutput("bar_chart"),
    DT::dataTableOutput("list_table")
  )
)


server <- function(input, output, session) {
  # Combine the selected variables into a new data frame
  selectedData <- reactive({
    iris %>% select(input$category, Species)
  })
  
  range <- reactive({
    data.frame(
      min <- selectedData() %>% select(-Species) %>% pull() %>% min(),
      max <-
        selectedData() %>% select(-Species) %>% pull() %>% max()
    )
  })
  
  plotData <- reactive({
    selectedData() %>%
      group_by(Species) %>%
      mutate(ncounts = n()) %>%
      select(ncounts, Species) %>%
      ungroup() %>%
      distinct()
  })
  
  output$bar_chart <- renderPlotly({
    exportTestValues(plotly_df = plotData())
    p <- plotData() %>%
      plot_ly(
        x = ~ Species,
        y = ~ ncounts,
        color = ~ Species,
        source = 'barplot',
        type = 'bar'
      ) %>%
      layout(showlegend = FALSE)
    
  })
  
  output$list_table <- DT::renderDataTable({
    bar_selected <- event_data("plotly_click", source = "barplot")
    
    if (is.null(bar_selected)) {
      df <- selectedData()
    } else {
      df <- selectedData() %>%
        filter(Species == !!bar_selected$x)
    }
    
    exportTestValues(display_dt = df)
    
    dt <- datatable(df,
                    selection = "none")
  })
}

shinyApp(ui = ui, server = server)
```

**testthat.R**
```r
library(testthat)

test_dir("tests/testthat")
```

**testthat/test-app.R**
```r
library(shinytest)
library(testthat)

app <- ShinyDriver$new("../../")

context("Check all input values in initial app state")

test_that("Check if clicking on plotly filters data table", {
  # Before clicking
  expected_before <- app$getAllValues()$export$display_dt
  expected_rows <- nrow(expected_before)
  expected_cur_rows <-
    ifelse(expected_rows >= 10, 10, expected_rows)
  
  expect_equal(last(app$getAllValues()$input$list_table_rows_all),
               expected_rows)
  expect_equal(last(app$getAllValues()$input$list_table_rows_current),
               expected_cur_rows)
  
  # Evoke clicking on first bar and check if value changed
  plot_content <- app$getAllValues()$export$plotly_df
  selected <- 1
  click_event <-
    sprintf(
      "[{\"curveNumber\":%d,\"pointNumber\":0,\"x\":\"%s\",\"y\":%d}]",
      selected,
      plot_content$Species[selected],
      plot_content$ncounts[selected]
    )
  app$setInputs(
    `.clientValue-plotly_click-barplot` = click_event,
    allowInputNoBinding_ = TRUE
  )
  expect_equal(app$getAllValues()$input$`.clientValue-plotly_click-barplot`,
               click_event)
  
  expected_after <- app$getAllValues()$export$display_dt
  
  # step to compare expected_before and expected_after
})
```

**Comment by hadley** [comment]
The issue is discussed at https://rstudio.github.io/shinytest/articles/in-depth.html#limitations-1
